name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app

      - name: Start xcodebuild test
        run: xcodebuild -project Carbon\ CapsBeeper.xcodeproj

      - name: Fix permissions
        run: chmod 755 build/Default/*.app/Contents/MacOS/*

      - name: Upload .app
        uses: actions/upload-artifact@v2
        with:
          name: CCB.app
          path: build/Default/*.app